title: Cesar's Ramirez CIT_481 Final Blog 10_2022

logo: /assets/img/jenkins.png
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
